export const TEMPO_ANIMACAO = 2000;
export const TEMPO_ANIMACAO_GRANDE = 4000;
export const TEMPO_DADOS_ROLANDO_SEGUNDOS = 2;
export const TEMPO_DADOS_ROLANDO_MILESIMOS = TEMPO_DADOS_ROLANDO_SEGUNDOS * 1000;
